#!/bin/bash
#
# Run this program in a window or the background, and it'll notify you if you 
# save something which is causing your tests to fail
#

main () {
    do_test
    while [ $RUN = 1 ]; do
        find lib bin tests -iname \*py -type f | inotifywait -e modify --fromfile - -q -q -t 3
        e=$?
        case $e in
        2)
            echo nop > /dev/null
            ;;
        1)
            do_test
            ;;
        *)
            echo 'unknown exit status: $e'
            exit 2
            ;;
        esac
    done

}

do_test () {
    for f in 1 1 1 1 1; do echo ''; done
    for f in 1 1 1 1 1; do echo '###############################################################'; done
    for f in 1 1 1 1 1; do echo ''; done
    nosetests-3.4 --rednose
    if [ $? -eq 0 ]; then
        notify-send 'Tests passed' "Project: ${PWD##*/}" -i '/usr/share/icons/Adwaita/48x48/emotes/face-smile.png' > /dev/null 2>&1
    else
        notify-send 'Tests FAILED' "Project: ${PWD##*/}" -i '/usr/share/icons/Adwaita/48x48/status/dialog-warning.png' > /dev/null 2>&1
        play ~/audio/misc/fart.wav > /dev/null 2>&1
    fi
}

trappy () {
    RUN=0
}

RUN=1
trap trappy INT HUP
main "$@"

