#!/bin/bash
#
# Run this program in a window or the background, and it'll notify you if you 
# save something which is causing your tests to fail
#

main () {
    PRJROOT="$(git rev-parse --show-toplevel)"
    export PYTHONPATH="$PRJROOT/lib:$PYTHONPATH"
    do_test
    while true; do
        inotifywait "$PRJROOT" -r -e modify --exclude '(\.swp$|/\.git/|\.py[cod]$)' > /dev/null 2>&1
        do_test
        sleep 1
    done
}

do_test () {
    for f in 1 1 1; do echo ''; done
    echo 'zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz'
    for f in 1 1 1; do echo ''; done
    python3 -m rednose 2> /dev/null && nosetests-3.4 --rednose || nosetests-3.4
    if [ $? -eq 0 ]; then
        notify-send 'Tests passed' "Project: ${PWD##*/}" -i '/usr/share/icons/Adwaita/48x48/emotes/face-smile.png' > /dev/null 2>&1
    else
        notify-send 'Tests FAILED' "Project: ${PWD##*/}" -i '/usr/share/icons/Adwaita/48x48/status/dialog-warning.png' > /dev/null 2>&1
        play ~/audio/misc/fart.wav > /dev/null 2>&1
    fi
}

main "$@"

